import UIKit

final class FavouritesViewController: UIViewController {
    private enum FavouriteItem { case template(category: TemplateCategory, subcategory: TemplateSubCategory, url: URL); case subcategory(category: TemplateCategory, subcategory: TemplateSubCategory) }
    @IBOutlet private weak var emptyStateView: UIView!
    @IBOutlet private weak var collectionView: UICollectionView!
    private var items:[FavouriteItem]=[]; private var allCategories:[TemplateCategory]=[]
    override func viewDidLoad(){super.viewDidLoad(); view.backgroundColor=AppColors.screenBackground; configureCollectionView(); NotificationCenter.default.addObserver(self,selector:#selector(reload),name:FavouritesManager.didChangeNotification,object:nil); loadCategories()}
    override func viewWillAppear(_ animated:Bool){super.viewWillAppear(animated); reload()}
    deinit{NotificationCenter.default.removeObserver(self)}
    private func configureCollectionView(){collectionView.backgroundColor=.clear; collectionView.dataSource=self; collectionView.delegate=self; collectionView.alwaysBounceVertical=true
        if let layout=collectionView.collectionViewLayout as? UICollectionViewFlowLayout{layout.estimatedItemSize=.zero; layout.minimumLineSpacing=12; layout.minimumInteritemSpacing=10; layout.sectionInset=UIEdgeInsets(top:12,left:12,bottom:20,right:12)}
        collectionView.register(UINib(nibName:"SubCategoryCardCell",bundle:nil),forCellWithReuseIdentifier:SubCategoryCardCell.reuseID); collectionView.register(HomeTemplatePreviewCell.self,forCellWithReuseIdentifier:HomeTemplatePreviewCell.reuseID)}
    private func loadCategories(){TemplateService.shared.fetchCategories{[weak self] result in guard let self else{return}; switch result{case .success(let categories):self.allCategories=categories.filter{$0.isVisibleInTemplateBrowser}.sorted{$0.Category_Index<$1.Category_Index}; self.reload(); case .failure(let error):print("Favourites failed to load categories: \(error)"); self.allCategories=[]; self.reload()}}}
    @objc private func reload(){guard isViewLoaded else{return}; let t=FavouritesManager.shared.favouritedTemplates(from:allCategories).map{FavouriteItem.template(category:$0.category,subcategory:$0.subcategory,url:$0.url)}; let s=FavouritesManager.shared.favouritedSubcategories(from:allCategories).map{FavouriteItem.subcategory(category:$0.category,subcategory:$0.subcategory)}; items=t+s; collectionView.reloadData(); collectionView.isHidden=false; emptyStateView.isHidden = !items.isEmpty}
    private func confirmRemove(category:TemplateCategory,subcategory:TemplateSubCategory){guard presentedViewController==nil else{return}; let a=UIAlertController(title:"Remove from Favourites?",message:"Do you want to remove \(subcategory.Subcategory_DisplayName) from your favourites?",preferredStyle:.alert); a.addAction(UIAlertAction(title:"No",style:.cancel)); a.addAction(UIAlertAction(title:"Remove",style:.destructive){[weak self] _ in FavouritesManager.shared.remove(subcategory,in:category); self?.reload()}); present(a,animated:true)}
    private func aspectRatio(for category:TemplateCategory)->CGFloat{let p=category.Category_Aspect_Ratio.split(separator:":"); guard p.count==2,let w=Double(p[0]),let h=Double(p[1]),w>0,h>0 else{return 1}; return CGFloat(h/w)}
}
extension FavouritesViewController:UICollectionViewDataSource,UICollectionViewDelegateFlowLayout{
    func collectionView(_ collectionView:UICollectionView,numberOfItemsInSection section:Int)->Int{items.count}
    func collectionView(_ collectionView:UICollectionView,cellForItemAt indexPath:IndexPath)->UICollectionViewCell{guard items.indices.contains(indexPath.item) else{return UICollectionViewCell()}; switch items[indexPath.item]{
    case .template(_,_,let url):guard let cell=collectionView.dequeueReusableCell(withReuseIdentifier:HomeTemplatePreviewCell.reuseID,for:indexPath) as? HomeTemplatePreviewCell else{return UICollectionViewCell()}; cell.configure(url:url,isFavourite:true); cell.onHeartTapped={FavouritesManager.shared.removeTemplate(url)}; return cell
    case .subcategory(let category,let subcategory):guard let cell=collectionView.dequeueReusableCell(withReuseIdentifier:SubCategoryCardCell.reuseID,for:indexPath) as? SubCategoryCardCell else{return UICollectionViewCell()}; cell.configure(subcategory:subcategory,isFavourite:true); cell.onHeartTapped={[weak self] in self?.confirmRemove(category:category,subcategory:subcategory)}; return cell}}
    func collectionView(_ collectionView:UICollectionView,layout collectionViewLayout:UICollectionViewLayout,sizeForItemAt indexPath:IndexPath)->CGSize{let available=max(0,collectionView.bounds.width-24-10); let width=floor(available/2); guard items.indices.contains(indexPath.item) else{return CGSize(width:width,height:width)}; switch items[indexPath.item]{case .template(let category,_,_):return CGSize(width:width,height:max(width*aspectRatio(for:category),80)); case .subcategory:return CGSize(width:width,height:SubCategoryCardCell.preferredHeight(for:width))}}
    func collectionView(_ collectionView:UICollectionView,didSelectItemAt indexPath:IndexPath){guard items.indices.contains(indexPath.item) else{return}; switch items[indexPath.item]{case .template:UnderConstruction.show(on:self,feature:"Editor canvas"); case .subcategory(let category,let subcategory):let gallery=TemplateGalleryViewController(category:category,subcategory:subcategory); if let navigationController{navigationController.pushViewController(gallery,animated:true)}else{present(UINavigationController(rootViewController:gallery),animated:true)}}}
}