import UIKit
final class TemplateGalleryViewController:UIViewController{
 private let category:TemplateCategory,subcategory:TemplateSubCategory,templateURLs:[URL],collectionView:UICollectionView;private let emptyLabel=UILabel()
 init(category:TemplateCategory,subcategory:TemplateSubCategory){self.category=category;self.subcategory=subcategory;templateURLs=subcategory.templateThumbnailURLs;let l=UICollectionViewFlowLayout();l.estimatedItemSize=.zero;l.minimumLineSpacing=12;l.minimumInteritemSpacing=10;l.sectionInset=UIEdgeInsets(top:12,left:12,bottom:24,right:12);collectionView=UICollectionView(frame:.zero,collectionViewLayout:l);super.init(nibName:nil,bundle:nil)}
 required init?(coder:NSCoder){fatalError("TemplateGalleryViewController is created in code")}
 override func viewDidLoad(){super.viewDidLoad();title=subcategory.Subcategory_DisplayName;view.backgroundColor=AppColors.screenBackground;navigationItem.largeTitleDisplayMode=.never;collectionView.translatesAutoresizingMaskIntoConstraints=false;collectionView.backgroundColor=.clear;collectionView.alwaysBounceVertical=true;collectionView.dataSource=self;collectionView.delegate=self;collectionView.register(TemplateThumbnailCell.self,forCellWithReuseIdentifier:TemplateThumbnailCell.reuseID);emptyLabel.translatesAutoresizingMaskIntoConstraints=false;emptyLabel.text="No templates are available in this section yet.";emptyLabel.textAlignment=.center;emptyLabel.textColor=AppColors.secondaryText;emptyLabel.numberOfLines=0;emptyLabel.isHidden = !templateURLs.isEmpty;view.addSubview(collectionView);view.addSubview(emptyLabel);NSLayoutConstraint.activate([collectionView.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor),collectionView.leadingAnchor.constraint(equalTo:view.leadingAnchor),collectionView.trailingAnchor.constraint(equalTo:view.trailingAnchor),collectionView.bottomAnchor.constraint(equalTo:view.bottomAnchor),emptyLabel.centerXAnchor.constraint(equalTo:view.centerXAnchor),emptyLabel.centerYAnchor.constraint(equalTo:view.centerYAnchor)]);NotificationCenter.default.addObserver(self,selector:#selector(favouritesChanged),name:FavouritesManager.didChangeNotification,object:nil)}
 override func viewWillAppear(_ animated:Bool){super.viewWillAppear(animated);navigationController?.setNavigationBarHidden(false,animated:animated);navigationController?.navigationBar.tintColor=AppColors.primaryText;collectionView.reloadData()} deinit{NotificationCenter.default.removeObserver(self)}
 @objc private func favouritesChanged(){guard isViewLoaded else{return};collectionView.reloadData()}
 private var templateAspectRatio:CGFloat{let p=category.Category_Aspect_Ratio.split(separator:":");guard p.count==2,let w=Double(p[0]),let h=Double(p[1]),w>0,h>0 else{return 1};return CGFloat(h/w)}
}
extension TemplateGalleryViewController:UICollectionViewDataSource,UICollectionViewDelegateFlowLayout{
 func collectionView(_ collectionView:UICollectionView,numberOfItemsInSection section:Int)->Int{templateURLs.count}
 func collectionView(_ collectionView:UICollectionView,cellForItemAt indexPath:IndexPath)->UICollectionViewCell{guard templateURLs.indices.contains(indexPath.item),let cell=collectionView.dequeueReusableCell(withReuseIdentifier:TemplateThumbnailCell.reuseID,for:indexPath) as? TemplateThumbnailCell else{return UICollectionViewCell()};let url=templateURLs[indexPath.item];cell.configure(url:url,isFavourite:FavouritesManager.shared.isTemplateFavourite(url));cell.onHeartTapped={FavouritesManager.shared.toggleTemplate(url)};return cell}
 func collectionView(_ collectionView:UICollectionView,layout collectionViewLayout:UICollectionViewLayout,sizeForItemAt indexPath:IndexPath)->CGSize{let w=floor(max(0,collectionView.bounds.width-34)/2);return CGSize(width:w,height:max(w*templateAspectRatio,80))}
 func collectionView(_ collectionView:UICollectionView,didSelectItemAt indexPath:IndexPath){UnderConstruction.show(on:self,feature:"Editor canvas")}
}
private final class TemplateThumbnailCell:UICollectionViewCell{
 static let reuseID="TemplateThumbnailCell";private let imageView=UIImageView(),activity=UIActivityIndicatorView(style:.medium),heart=UIButton(type:.system);private var task:URLSessionDataTask?,representedURL:URL?;var onHeartTapped:(()->Void)?
 override init(frame:CGRect){super.init(frame:frame);contentView.backgroundColor=AppColors.cardBackground;contentView.layer.cornerRadius=12;contentView.layer.masksToBounds=true;imageView.translatesAutoresizingMaskIntoConstraints=false;imageView.contentMode=.scaleAspectFill;imageView.clipsToBounds=true;activity.translatesAutoresizingMaskIntoConstraints=false;activity.hidesWhenStopped=true;heart.translatesAutoresizingMaskIntoConstraints=false;heart.backgroundColor=UIColor.systemBackground.withAlphaComponent(0.9);heart.layer.cornerRadius=17;heart.addTarget(self,action:#selector(tap),for:.touchUpInside);[imageView,activity,heart].forEach{contentView.addSubview($0)};NSLayoutConstraint.activate([imageView.topAnchor.constraint(equalTo:contentView.topAnchor),imageView.leadingAnchor.constraint(equalTo:contentView.leadingAnchor),imageView.trailingAnchor.constraint(equalTo:contentView.trailingAnchor),imageView.bottomAnchor.constraint(equalTo:contentView.bottomAnchor),activity.centerXAnchor.constraint(equalTo:contentView.centerXAnchor),activity.centerYAnchor.constraint(equalTo:contentView.centerYAnchor),heart.topAnchor.constraint(equalTo:contentView.topAnchor,constant:8),heart.trailingAnchor.constraint(equalTo:contentView.trailingAnchor,constant:-8),heart.widthAnchor.constraint(equalToConstant:34),heart.heightAnchor.constraint(equalToConstant:34)])}
 required init?(coder:NSCoder){fatalError()}
 override func prepareForReuse(){super.prepareForReuse();task?.cancel();representedURL=nil;imageView.image=nil;onHeartTapped=nil}
 func configure(url:URL,isFavourite:Bool){task?.cancel();representedURL=url;imageView.image=nil;activity.startAnimating();heart.setImage(UIImage(systemName:isFavourite ? "heart.fill":"heart"),for:.normal);heart.tintColor=isFavourite ? AppColors.favouriteHeartActive:AppColors.favouriteHeartInactive;task=ImageLoader.shared.load(url){[weak self] image in guard let self,self.representedURL==url else{return};self.activity.stopAnimating();self.imageView.image=image ?? UIImage(systemName:"photo")}}
 @objc private func tap(){onHeartTapped?()}
}