import UIKit
final class TemplateSearchViewController:UIViewController{
 private struct Result{let category:TemplateCategory;let subcategory:TemplateSubCategory}
 private let categories:[TemplateCategory];private var results:[Result]=[];private let searchField=UITextField();private let collectionView:UICollectionView;private let emptyLabel=UILabel()
 init(categories:[TemplateCategory]){self.categories=categories;let l=UICollectionViewFlowLayout();l.estimatedItemSize=.zero;l.minimumLineSpacing=12;l.minimumInteritemSpacing=10;l.sectionInset=UIEdgeInsets(top:12,left:12,bottom:20,right:12);collectionView=UICollectionView(frame:.zero,collectionViewLayout:l);super.init(nibName:nil,bundle:nil)}
 required init?(coder:NSCoder){fatalError("TemplateSearchViewController is created in code")}
 override func viewDidLoad(){super.viewDidLoad();title="Search";view.backgroundColor=AppColors.screenBackground;configureSearchField();configureCollectionView();configureEmptyState();NotificationCenter.default.addObserver(self,selector:#selector(reloadFavourites),name:FavouritesManager.didChangeNotification,object:nil)}
 override func viewDidAppear(_ animated:Bool){super.viewDidAppear(animated);focusSearchField()} deinit{NotificationCenter.default.removeObserver(self)}
 private func configureSearchField(){searchField.translatesAutoresizingMaskIntoConstraints=false;searchField.delegate=self;searchField.placeholder="Search templates";searchField.backgroundColor=.secondarySystemBackground;searchField.textColor=AppColors.primaryText;searchField.tintColor=AppColors.gradientStart;searchField.font=.systemFont(ofSize:16);searchField.layer.cornerRadius=12;searchField.layer.masksToBounds=true;searchField.autocapitalizationType=.none;searchField.autocorrectionType=.no;searchField.spellCheckingType=.no;searchField.returnKeyType=.search;searchField.clearButtonMode=.whileEditing
 let holder=UIView(frame:CGRect(x:0,y:0,width:40,height:44));let icon=UIImageView(image:UIImage(systemName:"magnifyingglass"));icon.tintColor=AppColors.secondaryText;icon.contentMode=.scaleAspectFit;icon.frame=CGRect(x:12,y:12,width:20,height:20);holder.addSubview(icon);searchField.leftView=holder;searchField.leftViewMode=.always;searchField.addTarget(self,action:#selector(searchTextChanged),for:.editingChanged);view.addSubview(searchField);NSLayoutConstraint.activate([searchField.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:8),searchField.leadingAnchor.constraint(equalTo:view.leadingAnchor,constant:12),searchField.trailingAnchor.constraint(equalTo:view.trailingAnchor,constant:-12),searchField.heightAnchor.constraint(equalToConstant:44)])}
 private func configureCollectionView(){collectionView.translatesAutoresizingMaskIntoConstraints=false;collectionView.backgroundColor=.clear;collectionView.keyboardDismissMode=.onDrag;collectionView.dataSource=self;collectionView.delegate=self;collectionView.register(UINib(nibName:"SubCategoryCardCell",bundle:nil),forCellWithReuseIdentifier:SubCategoryCardCell.reuseID);view.addSubview(collectionView);NSLayoutConstraint.activate([collectionView.topAnchor.constraint(equalTo:searchField.bottomAnchor,constant:6),collectionView.leadingAnchor.constraint(equalTo:view.leadingAnchor),collectionView.trailingAnchor.constraint(equalTo:view.trailingAnchor),collectionView.bottomAnchor.constraint(equalTo:view.bottomAnchor)])}
 private func configureEmptyState(){emptyLabel.translatesAutoresizingMaskIntoConstraints=false;emptyLabel.text="Start typing to search templates";emptyLabel.textAlignment=.center;emptyLabel.textColor=AppColors.secondaryText;emptyLabel.font=.systemFont(ofSize:15,weight:.medium);emptyLabel.numberOfLines=0;view.addSubview(emptyLabel);NSLayoutConstraint.activate([emptyLabel.centerXAnchor.constraint(equalTo:view.centerXAnchor),emptyLabel.centerYAnchor.constraint(equalTo:collectionView.centerYAnchor),emptyLabel.leadingAnchor.constraint(greaterThanOrEqualTo:view.leadingAnchor,constant:32),emptyLabel.trailingAnchor.constraint(lessThanOrEqualTo:view.trailingAnchor,constant:-32)])}
 private func focusSearchField(){DispatchQueue.main.asyncAfter(deadline:.now()+0.15){[weak self] in guard let self,self.view.window != nil else{return};if !self.searchField.becomeFirstResponder(){DispatchQueue.main.asyncAfter(deadline:.now()+0.15){[weak self] in _=self?.searchField.becomeFirstResponder()}}}}
 @objc private func searchTextChanged(){updateResults(for:searchField.text ?? "")};@objc private func reloadFavourites(){collectionView.reloadData()}
 private func updateResults(for query:String){let n=query.trimmingCharacters(in:.whitespacesAndNewlines);guard !n.isEmpty else{results=[];emptyLabel.text="Start typing to search templates";emptyLabel.isHidden=false;collectionView.reloadData();return};results=categories.flatMap{cat in cat.SubCategories.compactMap{sub in (cat.Category_Display_Name.localizedCaseInsensitiveContains(n)||sub.Subcategory_DisplayName.localizedCaseInsensitiveContains(n)) ? Result(category:cat,subcategory:sub):nil}};emptyLabel.text=results.isEmpty ? "No templates found for “\(n)”":nil;emptyLabel.isHidden = !results.isEmpty;collectionView.reloadData()}
}
extension TemplateSearchViewController:UITextFieldDelegate{func textFieldShouldReturn(_ textField:UITextField)->Bool{textField.resignFirstResponder();return true}}
extension TemplateSearchViewController:UICollectionViewDataSource,UICollectionViewDelegateFlowLayout{
 func collectionView(_ collectionView:UICollectionView,numberOfItemsInSection section:Int)->Int{results.count}
 func collectionView(_ collectionView:UICollectionView,cellForItemAt indexPath:IndexPath)->UICollectionViewCell{guard results.indices.contains(indexPath.item),let cell=collectionView.dequeueReusableCell(withReuseIdentifier:SubCategoryCardCell.reuseID,for:indexPath) as? SubCategoryCardCell else{return UICollectionViewCell()};let r=results[indexPath.item];cell.configure(subcategory:r.subcategory,isFavourite:FavouritesManager.shared.isFavourite(r.subcategory,in:r.category));cell.onHeartTapped={FavouritesManager.shared.toggle(r.subcategory,in:r.category)};return cell}
 func collectionView(_ collectionView:UICollectionView,layout collectionViewLayout:UICollectionViewLayout,sizeForItemAt indexPath:IndexPath)->CGSize{let w=floor(max(0,collectionView.bounds.width-34)/2);return CGSize(width:w,height:SubCategoryCardCell.preferredHeight(for:w))}
 func collectionView(_ collectionView:UICollectionView,didSelectItemAt indexPath:IndexPath){guard results.indices.contains(indexPath.item) else{return};let r=results[indexPath.item];navigationController?.pushViewController(TemplateGalleryViewController(category:r.category,subcategory:r.subcategory),animated:true)}
}